### PR TITLE
Fixed urls for many demos, added simple csw search, top/bottom selection to geosubset

### PR DESCRIPTION
**Pull request by rsignell-usgs**
I did these updates on a 1.0.x branch created from the nctoolbox-20130305 tag, as this is the version I've been using and sharing with others.   I fixed the URLS for many demos (demo 10 is still broken due to a broken MBARI URL), added a simple (hacked) CSW catalog search capability, added the ability to select the 'top' or 'bottom' layer with geosubset, and fixed some other bugs.   I'd like to eventually release this as 1.1.0.

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
@hohonuuli , please give this a look and also please ask questions before merging if any doubts as to what I'm trying to do here.   I *think* I'm doing what I want to accomplish in terms of moving to semantic versioning on github, and with a branch for every major release, but not 100% sure about it.

**Comment by rsignell-usgs** [comment]
@drf5n , it would be great if you could give this a test-drive also.

**Comment by hohonuuli** [comment]
I just started stepping through the code. One thing that jumped out right away is that ncgeovariable's grid_interop method does __nothing__ for _GeoX_ coordinates, the whole block is commented out. Is this your intent?

**Comment by rsignell-usgs** [comment]
I didn't change that part of the code.   it did nothing before, and it still does nothing.

**Pull request merged**
