### PR TITLE
ncgeovariable.m:grid_interop -- pass unrecognized GeoZ coordinates 

### PR DESCRIPTION
**Pull request by drf5n**
ncgeovariable.m:grid_interop -- pass GeoZ coordinates when unrecognized by ucar.nc2.dt.grid.GridDataset.findGridByName.   

Aimed at issue #65.

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
I don't think #65 is a bug, so not merging. 
@drf5n, comments?

**Comment by drf5n** [comment]
More comments on #65.  Basically:  GeoZ  ocean* axes are the only ones that are tested for CF-compliance at the variable level and they fault hard and ugly, while all the other non GeoZ ocean ones are tested at the axes level for CF compliance.   If they fail, they are passed through unmolested. 

This patch brings non-CF GeoZ ocean coordinate behavior in-line with the behavior for the other non-CF conformant axes and also with the help documentation.

**Comment by rsignell-usgs** [comment]
Ah, okay, I get it now.  Sounds good to me then.  @hohonuuli , do you have any issues with this?

**Comment by hohonuuli** [comment]
I do not. Do we have a demo written to illustrate the use/need of this change? If not, and you can find the time to squeeze it in, can one of you write a short one and drop it in the demos directory? That way we have something to test the expected behavior with.

**Comment by drf5n** [comment]
I added demos/geodemo_1e.m, which is pretty much geodemo_1a.m on a less compliant dataset.

**Comment by hohonuuli** [comment]
@drf5n Thanks!

**Comment by drf5n** [comment]
I toned the warning down a bit and make it more informative.  Do we even need a warning if the other axes don't warn on it?

**Comment by hohonuuli** [comment]
I don't see that change. You might have to submit another pull request. That warning does seem rather harsh doesn't it. As to whether or not we should inform users of a missing axis, well, that's up to you and Rich. I don't have a dog in this fight.

**Comment by rsignell-usgs** [comment]
I don't really like warnings, so I vote minimal.

**Comment by drf5n** [comment]
#67 is a new pull request removing the warning.  

If there were to be any warnings, they would belong in the outer loop at https://github.com/nctoolbox/nctoolbox/blob/master/cdm/ncgeovariable.m#L180

**Pull request merged**
